//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDTS.Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendar
    {
        public calendar()
        {
            this.trips = new HashSet<trip>();
        }
    
        public int service_id { get; set; }
        public bool sunday { get; set; }
        public bool monday { get; set; }
        public bool tuesday { get; set; }
        public bool wednesday { get; set; }
        public bool thrusday { get; set; }
        public bool friday { get; set; }
        public bool saturday { get; set; }
        public System.DateTime starting_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual ICollection<trip> trips { get; set; }
    }
}
