//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDTS.Data_Access_Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class publicTransportDataEntities : DbContext
    {
        public publicTransportDataEntities()
            : base("name=publicTransportDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<agency> agencies { get; set; }
        public DbSet<calendar> calendars { get; set; }
        public DbSet<routesInfo> routesInfoes { get; set; }
        public DbSet<shape> shapes { get; set; }
        public DbSet<stop> stops { get; set; }
        public DbSet<translation> translations { get; set; }
        public DbSet<trip> trips { get; set; }
        public DbSet<stop_times> stop_times { get; set; }
    }
}
