//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDTS.Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stop_times
    {
        public string trip_id { get; set; }
        public System.TimeSpan arrival_time { get; set; }
        public System.TimeSpan departure_time { get; set; }
        public int stop_id { get; set; }
        public int stop_sequence { get; set; }
        public int pickup_type { get; set; }
        public int drop_off_type { get; set; }
    
        public virtual stop stop { get; set; }
        public virtual trip trip { get; set; }
    }
}
