//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDTS.Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stop
    {
        public stop()
        {
            this.stop_times = new HashSet<stop_times>();
        }
    
        public int stop_id { get; set; }
        public int stop_code { get; set; }
        public string stop_name { get; set; }
        public string stop_desc { get; set; }
    
        public virtual ICollection<stop_times> stop_times { get; set; }
    }
}
