//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDTS.Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class translation
    {
        public int trans_id { get; set; }
        public bool lang { get; set; }
        public string translation1 { get; set; }
    }
}
