//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDTS.Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        public trip()
        {
            this.stop_times = new HashSet<stop_times>();
        }
    
        public int route_id { get; set; }
        public int service_id { get; set; }
        public string trip_id { get; set; }
        public int direction_id { get; set; }
        public Nullable<int> shape_id { get; set; }
    
        public virtual calendar calendar { get; set; }
        public virtual routesInfo routesInfo { get; set; }
        public virtual shape shape { get; set; }
        public virtual ICollection<stop_times> stop_times { get; set; }
    }
}
